version: '3.7'
services:
  shellcheck:
    image: koalaman/shellcheck:latest
    command: -x lib/bats-helper.bash hooks/environment hooks/post-checkout hooks/pre-checkout hooks/pre-exit configure.sh
    working_dir: /plugin
    volumes:
      - ".:/plugin"

  unittest:
    build:
      context: .
    command: sh -c "coverage run --source=bk_ssm_secrets --omit='*/tests/*' -m unittest && coverage report -m"
    working_dir: /plugin
    volumes:
      - ".:/plugin"