name: "Paramterstore Secrets"
description: "Expose build secrets stored in AWS Systems Manager Paramterstore to your jobs"
author: "@mikeknox"
public: true
requirements:
  - curl
  - bash
  - aws
configuration:
  properties:
    path:
      type: string
  required:
    - path
  additionalProperties: false

